name             'data-bag-cache'
maintainer       'Norman Joyner'
maintainer_email 'norman.joyner@gmail.com'
license          'All rights reserved'
description      'Installs/Configures data-bag-cache'
long_description 'Installs/Configures data-bag-cache'
version			'0.1.1'
